### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by mdbraber** [Nukesor/hetznerbot#1]
Hi,

I've tried both your bot and installed my own but it seems that the layout of the SB page has changed. Is it still working for you or should I dive into the parsing of the page to see what changed?

Thanks!

**Comment by Nukesor** [comment]
You're right.
This needs some bigger changes, but it will be a lot nicer, since the new layout gets a single json file with ALL auction elements.
I just need to spend a few hours fixing this. Hopefully I'll get to do this, this weekend or next week.

**Comment by Nukesor** [comment]
Hey! 
Hetznerbot is running again. And everything is faster and better than before ;)
