### ISSUE TITLE
Telegram bot offline?

### ISSUE THREAD

**Issue by dandud100** [Nukesor/hetznerbot#15]
Hey, I wanted to give your bot a try, but it does not respond. Is is currently offline?

**Comment by dandud100** [comment]
![Uploading Screenshot_20230526-103550_Telegram.png…]()

**Comment by daniel22-git** [comment]
![Screenshot_20230526-103550_Telegram](https://github.com/Nukesor/hetznerbot/assets/43549788/059ed951-5184-4ec9-97b6-dd38049732eb)

**Comment by Nukesor** [comment]
The bot is now "private" and only usable by a small number of authenticated users.
If you like to use it, just host your own instance :).

**Comment by daniel22-git** [comment]
Oh that's sad, maybe update your GitHub readme then. 👍🏻

**Comment by Nukesor** [comment]
Ohh damn. I thought I deleted all of those references. Sorry :sweat:
