### ISSUE TITLE
[Noob] Problem installing it

### ISSUE THREAD

**Issue by nobewayo** [Nukesor/hetznerbot#8]
Sad to see you've taken the bot down, just started using it yesterday and I'm a noob with Linux lol 

When running just setup it fails with this error message:

```
Package operations: 16 installs, 0 updates, 0 removals

  • Installing tornado (6.1): Failed

  EnvCommandError

  Command ['/root/.cache/pypoetry/virtualenvs/hetznerbot-Qf3vyu88-py3.10/bin/pip', 'install', '--no-deps', 'file:///root/.cache/pypoetry/artifacts/c1/d5/3e/d4647a424038d7e17d19c3543aecbc1d78232b69c68f4cd95a90196a6b/tornado-6.1.tar.gz'] errored with the following return code 1, and output:
  Processing /root/.cache/pypoetry/artifacts/c1/d5/3e/d4647a424038d7e17d19c3543aecbc1d78232b69c68f4cd95a90196a6b/tornado-6.1.tar.gz
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    error: subprocess-exited-with-error

    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [1 lines of output]
        ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed

  × Encountered error while generating package metadata.
  ╰─> See above for output.

  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.


  at /usr/lib/python3/dist-packages/poetry/utils/env.py:1183 in _run
      1179│                 output = subprocess.check_output(
      1180│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1181│                 )
      1182│         except CalledProcessError as e:
    → 1183│             raise EnvCommandError(e, input=input_)
      1184│
      1185│         return decode(output)
      1186│
      1187│     def execute(self, bin, *args, **kwargs):

error: Recipe `setup` failed on line 14 with exit code 1

```

Can you point me to what I'm doing wrong?

**Comment by Nukesor** [comment]
Actually I already took it down years ago. There was just a bug in the code that allowed users without usernames to continue using it ;D. Your recent comment just made aware of this bug.

To get better in a linux/programming environment, I would heartily suggest to learn reading error messages. Error messages tell you 95% of the time what the actual problem is.

From there on, it's pretty easy to find out how to fix it.

```
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [1 lines of output]
        ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
        [end of output]
```

So it looks like `setuptools` is not installed on your environment.
There's most likely a python-setuptools package for your distribution, or you could try to add the setuptools package to the `pyproject.toml` and add it as a dependency.

**Comment by nobewayo** [comment]
I actually fixed it.. However, when running just initdb I get this errormessage instead:


poetry run python main.py initdb
Traceback (most recent call last):
  File "/home/ubuntu/hetznerbot/main.py", line 8, in <module>
    from hetznerbot.config import config
  File "/home/ubuntu/hetznerbot/hetznerbot/config.py", line 32, in <module>
    with open(config_path, "w") as file_descriptor:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.config/hetznerbot.toml'
error: Recipe `initdb` failed on line 7 with exit code 1


Seems like no config file was created, however, just setup ran without any errors.. :(

**Comment by nobewayo** [comment]
Would you maybe be interested in letting me use it for a week or two, for a fee? Or set it up on my VPS for a fee.

**Comment by Nukesor** [comment]
Sorry, I already have enough to do on my plate ;)

Try to dig around and learn a bit about python, telegram bots and app development, it's quite interesting!

I'm already providing the code of the project and convenience functions for setting it up, the rest is up to the individuals that want to use it ;)
